services:
  nix:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/nocturne-image
      - nix-store:/nix
      - nix-root:/root
    stdin_open: true
    tty: true

volumes:
  nix-store:
  nix-root:
